### ISSUE TITLE
Include a parsing function to simplify configuration files

### ISSUE THREAD

**Issue by asier-izquierdo** [asier-izquierdo/craftceres#25]
The scripts should include a parsing function to improve readability on the configuration files. This would allow the following current declaration syntax:

```
papermc_path="<path to the papermc.jar parent directory>"
tmux_session_name="papermc"
tmux_session_path="<path to the tmux session location>"
```

To be written as:

```
required:  
  papermc:  
    path: /home/user/craftceres
  tmux_session:
    name: papermc
    path: /tmp/tmux-1001/default
```

A possibility would be to implement [Stefan Farestam's YAML parser function](https://stackoverflow.com/questions/5014632/how-can-i-parse-a-yaml-file-from-a-linux-shell-script/21189044#21189044)

Furthermore, it would simplify the optional functions usage, going from:

```
###########################################################################################
# Setting the corresponding values will enable the reporter, otherwise it will just show  #
# a warning, indicating that it is not enabled.                                           #
# Only 'TOKEN' should be replaced with the API token the BotFather generated              #
###########################################################################################

# bot_url="https://api.telegram.org/botTOKEN/sendMessage"
# chat_id="<ID of the chat with the bot>"
```

Where we need to explain that the variables should be set and uncommented for the function to activate, to the better:

```
optional:
  telegram_reporter:
    enabled: yes
    token: k34256T2LwIGBU35I6g
    id: 968124586
```
